language: java

jobs:
  include:
    - stage: compile
      script: mvn -Dcomision=10 compile
    - stage: test
      script: mvn -Dcomision=10 test
    - stage: package
      script: mvn -Dcomision=10 package
